export const READ_JSON_REQUEST = "READ_JSON_REQUEST";
export const READ_JSON_FAILURE = "READ_JSON_FAILURE";
export const READ_JSON_SUCCESS = "READ_JSON_SUCCESS";

export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";

export const REMOVE_TODO_REQUEST = "REMOVE_TODO_REQUEST";
export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";
export const REMOVE_TODO_FAILURE = "REMOVE_TODO_FAILURE";

export const CHANGE_TODO_REQUEST = "CHANGE_TODO_REQUEST";
export const CHANGE_TODO_FAILURE = "CHANGE_TODO_FAILURE";
export const CHANGE_TODO_SUCCESS = "CHANGE_TODO_SUCCESS";

export const FILTER_TODO_REQUEST = "FILTER_TODO_REQUEST";
export const FILTER_TODO_FAILURE = "FILTER_TODO_FAILURE";
export const FILTER_TODO_SUCCESS = "FILTER_TODO_SUCCESS";

